sudo: required
services:
- docker
language: bash
install:
- docker build -t kextract .
- mkdir dist
# As building process using a travis vm instead of container is expensive,
# use a list of build commands instead of a build matrix.
script:
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract amd64 jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract arm64 jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract armhf jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract i386 jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract powerpc jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract ppc64el jessie
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract amd64 stretch
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract arm64 stretch
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract armhf stretch
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract i386 stretch
- docker run --rm -ti -v $(pwd)/dist:/workdir kextract ppc64el stretch
before_deploy:
- sudo chmod 755 ./dist
- sudo chmod 644 ./dist/*
- sudo chown -R travis:travis ./dist
- ls -al ./dist/
deploy:
  provider: releases
  api_key:
    secure: tT5vs/hMarrQ0CZjV92GQPe+iXKngA6q9/k2cm/Cnc1LhVtsy4/vSV+ykLLYwkphevzVVSaHZm2aj6V+mtt8YbiH7mMXhp/+oMJJvDi1kdSFfgyCHhn9yIY7RarZKkejb7VL8zZ7dDkkl7Ww249CSex9dOpK10tuNgEP6f3zdDSzbzzmEtth03itEL/QeA9IyW03WthBMsN7802WX5TnHnS1FJQx/a744J3usi5o486Ol+1uQlFaSHU6556V6lrRH1Bln3zDrGjHsN+ZQN1CsEWyb22i6P3hdqwbA/r9d4FLXkke5xVvGMDZA+XXjkn3oNp8oh3XGV8OxOcx5dd/ZffX9AwMyn0BrWQEalUfR79NGUf7boIub/aBiHXqCuygYbWm4bFZ+FlX4cG66VyinB5mYGOe7d36PgVAblX7fLAwWpXLF9UY8cKBrM0W8/om77WATyqZnesb9cyEChtIiQMG1eIsZk7mnrw9g1NJG9R+Vt6FyRowVIW6JRWbwzduVdr5WBz9CsqiK4qPZ6CJEP1bc4RmQZvwd0nJU7qUEDwPS8kqlVp4Q68qki63S54KGpwdvKspOkpYFyqgrfD8EtTbX8ht/VE84R7xr9y0hySVBMS06heHhUyY50BxkT6iNRNzU9qD/6nrC6+3FkcBAk6ADzZqc7fzlw8PJSBfyek=
  skip_cleanup: true
  file_glob: true
  file: "./dist/*"
  on:
    repo: nlm/kextract-debianinstaller
    tags: on
